version: '3'

services:
  minerrig1_graphite:
    image: graphiteapp/graphite-statsd:latest
    depends_on:
      - minerrig1_rabbitmq
    expose:
      - "80"
    ports:
      - "2003:2003"
      - "8080:80"
    volumes:
      - $PWD/graphite-conf/carbon.conf:/opt/graphite/conf/carbon.conf
      - $PWD/graphite-conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
      - $PWD/graphite-conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
  minerrig1_grafana:
    image: grafana/grafana:latest
    environment:
      - GF_DEFAULT_INSTANCE_NAME=minerrig1
      - GF_SECURITY_ADMIN_USER=minerrig1
      - GF_SECURITY_ADMIN_PASSWORD=Qgjk5234
      - GF_SERVER_ROOT_URL=http://grafana.server.name
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,grafana-simple-json-datasource  1.2.3
    ports:
      - "3000:3000"
    depends_on:
      - minerrig1_graphite
  minerrig1_rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    environment: 
      - RABBITMQ_DEFAULT_USER=minerrig1
      - RABBITMQ_DEFAULT_PASS=Qgjk5234
  minerrig1_rabbit_forwarder:
    build: ./rabbit-forwarder
    environment:
      - CARBON_HOST=minerrig1_graphite
      - CARBON_PORT=2003
      - RABBIT_URL=amqp://minerrig1:Qgjk5234@minerrig1_rabbitmq:5672/%2F
      - RABBIT_EXCHANGE_NAME=exchange
      - RABBIT_QUEUE_NAME=queue
      - POOL_API_HOST=https://api.ethermine.org
      - WALLET_ADDRESS=aa32e28bb20a1f8fcde8c24c6f4d0a84c64f4c80
      - POOL_POLLING_SCHEDULE=*/5 * * * *
    depends_on:
      - minerrig1_graphite
      - minerrig1_rabbitmq
